language: swift
os: osx
osx_image: xcode11.4
compiler: gcc

_shared_script:
  script: &1
  - pip install -U pip
  - pip install awscli
  - brew install ninja
  - cmake -GNinja ${MYTOOLCHAIN} -S ./deps/ziti-sdk-c -B ./deps/ziti-sdk-c/build-${MYSDK}-${MYARCH}
  - ninja -C ./deps/ziti-sdk-c/build-${MYSDK}-${MYARCH}
  - xcodebuild build -configuration Release -scheme ${MYSCHEME} -derivedDataPath ./DerivedData/CZiti -arch ${MYARCH} -sdk ${MYSDK}
  - MYLIBDIR="DerivedData/CZiti/Build/Products/${MYCFGSDK}"
  - aws s3 sync "${TRAVIS_BUILD_DIR}/${MYLIBDIR}" s3://ziti-sdk-swift/${MYLIBDIR} --delete
  - MYDSDIR="DerivedData/CZiti/Build/Intermediates.noindex/CZiti.build/${MFCFGSDK}/${MYSCHEME}/DerivedSoures"
  - aws s3 sync "${TRAVIS_BILD_DIR}/${MYDSDIR}" s3://ziti-sdk-swift/${MYDSDIR} --delete

jobs:
  include:
  - stage: build
    env: MYSCHEME="CZiti-macOS" MYARCH="x86_64" MYSDK="macosx" MYTOOLCHAIN="" MYCFGSDK="Release"
    script: *1

  - stage: 
    env: MYSCHEME="CZiti-iOS" MYARCH="arm64" MYSDK="iphoneos" MYTOOLCHAIN="-DCMAKE_TOOLCHAIN_FILE=../toolchains/iOS-arm64.cmake" MYCFGSDK="Release-iphoneos"
    script: *1

  - stage: 
    env: MYSCHEME="CZiti-iOS" MYARCH="x86_64" MYSDK="iphonesimulator" MYTOOLCHAIN="-DCMAKE_TOOLCHAIN_FILE=../toolchains/iOS-x86_64.cmake"
      MYCFGSDK="Release-iphonesimulator"
    script: *1

  - stage: after_build
    script:
      - aws s3 sync s3://ziti-sdk-swift/DerivedData .
      - ls -lart
