language: swift
os: osx
osx_image: xcode11.4
compiler: gcc

install:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - brew install ninja
  - gem install jazzy
  - export PATH=~/bin:$PATH
  - echo ${gh_ci_key} | base64 --decode > github_deploy_key
  - chmod 600 github_deploy_key
  - md5sum github_deploy_key
  - git config user.name ziti-ci
  - git config user.email ziti-ci@netfoundry.io
  - git config core.sshCommand "ssh -i github_deploy_key"
  - git remote set-url origin git@github.com:${TRAVIS_REPO_SLUG}

cache:
  directories:
    - $HOME/.rvm/

stages:
  - name: prepare cache
  - name: build
  - name: make dist
  - name: tag and publish
    if: branch = master and type != pull_request

_shared_script:
  script: &1
  - ./ci_deps_cache.sh ${MYSDK} ${MYARCH} ${MYTOOLCHAIN}
  - xcodebuild build -configuration Release -scheme ${MYSCHEME} -derivedDataPath ./DerivedData/CZiti -arch ${MYARCH} -sdk ${MYSDK}
  - MYLIBDIR="DerivedData/CZiti/Build/Products/${MYCFGSDK}"
  - aws s3 sync "${TRAVIS_BUILD_DIR}/${MYLIBDIR}" s3://ziti-sdk-swift/DerivedData-${TRAVIS_BUILD_NUMBER}/${MYLIBDIR} --delete
  - MYDSDIR="DerivedData/CZiti/Build/Intermediates.noindex/CZiti.build/${MYCFGSDK}/${MYSCHEME}.build/DerivedSources"
  - aws s3 sync "${TRAVIS_BUILD_DIR}/${MYDSDIR}" s3://ziti-sdk-swift/DerivedData-${TRAVIS_BUILD_NUMBER}/${MYDSDIR} --delete

jobs:
  include:
  - stage: prepare cache
    script: true
  - stage: build
    env: 
      - MYSDK="macosx" 
      - MYSCHEME="CZiti-macOS" 
      - MYARCH="x86_64" 
      - MYTOOLCHAIN="" 
      - MYCFGSDK="Release"
    script: *1
    after_script:
      - jazzy
      - aws s3 sync ./docs s3://ziti-sdk-swift/${TRAVIS_BUILD_NUMBER}/docs

  - stage: 
    env: 
      - MYSDK="iphoneos" 
      - MYSCHEME="CZiti-iOS" 
      - MYARCH="arm64" 
      - MYTOOLCHAIN="-DCMAKE_TOOLCHAIN_FILE=../toolchains/iOS-arm64.cmake" 
      - MYCFGSDK="Release-iphoneos"
    script: *1

  - stage: 
    env: 
      - MYSDK="iphonesimulator" 
      - MYSCHEME="CZiti-iOS" 
      - MYARCH="x86_64" 
      - MYTOOLCHAIN="-DCMAKE_TOOLCHAIN_FILE=../toolchains/iOS-x86_64.cmake" 
      - MYCFGSDK="Release-iphonesimulator"
    script: *1

  - stage: make dist
    script: 
      - aws s3 sync s3://ziti-sdk-swift/DerivedData-${TRAVIS_BUILD_NUMBER}/DerivedData ./DerivedData
      - ./make_dist.sh
      - aws s3 sync ./dist s3://ziti-sdk-swift/${TRAVIS_BUILD_NUMBER}
      - aws s3 rm --recursive s3://ziti-sdk-swift/DerivedData-${TRAVIS_BUILD_NUMBER}

  - stage: tag and publish
    script:
      - ./tagIfNeeded.sh
      - aws s3 sync s3://ziti-sdk-swift/${TRAVIS_BUILD_NUMBER} ./dist
      - ls -lat ./dist
      - echo "TODO publish and rm --recursive s3://ziti-sdk-swift/${TRAVIS_BUILD_NUMBER}"
      - git push --tags --verbose
